# Generated by Django 5.1.1 on 2024-09-08 12:02

import text.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('video', models.FileField(upload_to='video', validators=[text.models.validate_video_extension])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='text_video_created_614d1f_idx'),
        ),
    ]
